# Generated by Django 5.2.3 on 2025-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_create_user_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('credit_card', 'Credit Card'), ('cod', 'Cash on Delivery')], default='credit_card', max_length=20),
        ),
    ]
