# Generated by Django 5.2.3 on 2025-06-15 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='comment',
            field=models.TextField(blank=True),
        ),
    ]
