# Generated by Django 5.2.3 on 2025-06-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_cartitem_price_product_discount_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Offer name (e.g., 'Summer Sale 20% Off')", max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the offer')),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage Discount'), ('fixed', 'Fixed Amount Discount'), ('free_shipping', 'Free Shipping'), ('buy_one_get_one', 'Buy One Get One')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='Discount percentage or fixed amount', max_digits=5)),
                ('apply_to', models.CharField(choices=[('all_products', 'All Products'), ('specific_categories', 'Specific Categories'), ('specific_products', 'Specific Products'), ('material_type', 'Material Type')], default='all_products', max_length=20)),
                ('material_type', models.CharField(blank=True, help_text="Material type (e.g., 'Gold', 'Silver') if applying to material type", max_length=50)),
                ('min_order_amount', models.DecimalField(decimal_places=2, default=0, help_text='Minimum order amount to qualify for this offer', max_digits=10)),
                ('max_discount_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Maximum discount amount (leave blank for no limit)', max_digits=10, null=True)),
                ('start_date', models.DateTimeField(help_text='When the offer starts')),
                ('end_date', models.DateTimeField(help_text='When the offer ends')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this offer')),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Show this offer on the homepage banner')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('categories', models.ManyToManyField(blank=True, help_text='Select categories if applying to specific categories', to='shop.category')),
                ('products', models.ManyToManyField(blank=True, help_text='Select products if applying to specific products', to='shop.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
