# Generated by Django 5.2.3 on 2025-06-18 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_discount_delete_specialoffer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Customer name', max_length=100)),
                ('location', models.CharField(help_text='Customer location (e.g., Mumbai, Delhi)', max_length=100)),
                ('rating', models.IntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], default=5, help_text='Customer rating (1-5 stars)')),
                ('comment', models.TextField(help_text='Customer testimonial/review')),
                ('is_active', models.BooleanField(default=True, help_text='Show this testimonial on homepage')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers show first)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
    ]
