# Generated by Django 5.2.3 on 2025-06-18 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='last_viewed',
            field=models.DateTimeField(blank=True, help_text='Last time product was viewed', null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='views_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times product was viewed'),
        ),
    ]
